version: '2'
services:
    mysql:
      image: mysql-image-service
      container_name: mysql-service
      ports:
         - "127.0.0.1:7000:3306/tcp"
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: ServicioWeb
        MYSQL_USER: adminuser
        MYSQL_PASSWORD: adminuser
      volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data: